Feature/tests
ArmaForces/Website pull request #113
Opened 2020-10-31 15:46 UTC by jskowronski39

This will:
* add some basic unit and integration tests
* add PHP Unit to CI pipeline

2020-10-31 18:24 UTC, veteran29 commented on tests/integration/Service/SteamWorkshop/SteamWorkshopClientTest.php
> + * @@covers \App\Service\SteamWorkshop\SteamWorkshopClient
```suggestion
 * @covers \App\Service\SteamWorkshop\SteamWorkshopClient
```

2020-12-13 12:59 UTC, jskowronski39 commented on tests/integration/Service/SteamWorkshop/SteamWorkshopClientTest.php
> + * @@covers \App\Service\SteamWorkshop\SteamWorkshopClient
Fixed

2020-12-22 22:45 UTC, veteran29 requested changes

2020-12-22 22:45 UTC, veteran29 commented on .github/workflows/docker.yml
> -            - uses: actions/checkout@v1
Unnecessary whitespace changes.

2020-12-22 22:45 UTC, veteran29 commented on .github/workflows/security.yml
> +            -   uses: symfonycorp/security-checker-action@v2
Unnecessary whitespace changes.

2020-12-22 22:45 UTC, veteran29 commented on .github/workflows/tests.yml
> +            -   name: Checkout branch
One space after dash.

2020-12-22 22:45 UTC, veteran29 commented on .github/workflows/tests.yml
> +                uses: MilesChou/composer-action/7.4/install@master
Please use tagged version instead of master if possible.

2020-12-22 22:45 UTC, veteran29 commented on tests/unit/Service/SteamWorkshop/Helper/SteamWorkshopHelperTest.php
> +        static::assertSame(self::ITEM_ID, $itemUrl);
```suggestion
        $itemId = SteamWorkshopHelper::itemUrlToItemId($itemUrl);
        static::assertSame(self::ITEM_ID, $itemId);
```

2020-12-22 23:04 UTC, veteran29 approved these changes

2020-12-22 23:06 UTC, merged